### ISSUE TITLE
"ERROR: URL was invalid" script doesnt work, tried it with different links, could you fix it please?

### ISSUE THREAD

**Issue by JohnTrunix** [yasoob/watchcartoononline-dl#23]

**Comment by fabianmendes** [comment]
Yes, please. It seems to be because of this:
![image](https://user-images.githubusercontent.com/31230743/119688302-df9b0000-be15-11eb-9935-964eadc8148f.png)

Otherwise, AMAZING project! @heniotierra  Haha, I've just made one similar but it's for another website. It is not user-friendly yet, but It does work! ←https://github.com/fabianmendes/megacartoonet-links

**Comment by heniotierra** [comment]
Hey again @fabianmendes ! ^^
Thanks for the debugging on this. I will see if I can get to this when I get some free time.

**Comment by fabianmendes** [comment]
All right, thanks and there is no rush. I would like to help but I am not
so familiar with python 2 hehe. Glad to hear from you!

Greetings,
 ~V. Fabian T· Mendes C.
